apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/ingress.yml
      # - ./k8s/zone-manager-deployment.yml
      # - ./k8s/zone-manager-cluster-ip.yml
      - ./k8s/zone-node-stateful-set.yml
      # - ./k8s/zone-node-headless-service.yml
      # - ./k8s/proxy-node-deployment.yml
      # - ./k8s/proxy-node-cluster-ip.yml
      # - ./k8s/player-client-deployment.yml
      # - ./k8s/player-client-cluster-ip.yml
      # - ./k8s/zone-node-hpa.yml
      - ./k8s/redis-deployment.yml
      - ./k8s/redis-cluster-ip.yml
      # - ./k8s/postgres-statefulset.yml
      # - ./k8s/postgres-cluster-ip.yml
      # - ./k8s/postgres-persistent-volume.yml
      # - ./k8s/postgres-persistent-volume-claim.yml
      # - ./k8s/database-node-statefulset.yml
      # - ./k8s/database-node-headless-service.yml
build:
  local:
    push: false
  artifacts:
    - image: snowd3n/permadeath-proxy-node
      context: .
      docker:
        dockerfile: dockerfiles/proxy-node.dev.Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.json"
    - image: snowd3n/permadeath-zone-node
      context: .
      docker:
        dockerfile: dockerfiles/zone-node.dev.Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.json"
    - image: snowd3n/permadeath-zone-manager
      context: .
      docker:
        dockerfile: dockerfiles/zone-manager.dev.Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.json"
    - image: snowd3n/permadeath-player-client
      context: .
      docker:
        dockerfile: dockerfiles/player-client.dev.Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.json"
          - "**/*.css"
    # - image: snowd3n/permadeath-database-node
    #   context: .
    #   docker:
    #     dockerfile: dockerfiles/database-node.dev.Dockerfile
    #   sync:
    #     infer: ["**/*"]
# portForward:
#   - resourceType: deployment
#     resourceName: pc-test
#     port: 3000
# - image: snowd3n/permadeath-database-node
#   context: .
#   docker:
#     dockerfile: dockerfiles/database-node.dev.Dockerfile
#   sync:
#     infer: ["**/*"]
