apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-node-statefulset
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      component: database-node
  template:
    metadata:
      labels:
        component: database-node
    spec:
      containers:
        - name: database-node
          image: snowd3n/permadeath-database-node
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PG_USER
              value: postgres
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: postgres
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PG_PASSWORD
