apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy-node
  template:
    metadata:
      labels:
        component: proxy-node
    spec:
      containers:
        - name: proxy-node
          image: snowd3n/permadeath-proxy-node
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "80"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: "6379"
