apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zone-node-stateful-set
spec:
  serviceName: zone-node
  replicas: 2
  selector:
    matchLabels:
      component: zone-node
  template:
    metadata:
      labels:
        component: zone-node
    spec:
      containers:
        - name: zone-node
          image: snowd3n/permadeath-zone-node
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1000m
          env:
            - name: PORT
              value: "80"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: redis-cluster-ip
            - name: REDIS_PORT
              value: "6379"
