apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zone-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: zone-node-stateful-set
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
